# Generated by Django 4.0 on 2022-12-28 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_highlight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowing',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalog.user', to_field='username'),
        ),
    ]
