# Generated by Django 4.0 on 2022-12-28 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_borrowing_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='isReturned',
            field=models.BooleanField(default=False),
        ),
    ]
