# Generated by Django 4.0 on 2022-12-28 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_book_isreturned'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='isReturned',
        ),
        migrations.AlterField(
            model_name='borrowing',
            name='isReturned',
            field=models.BooleanField(default=False),
        ),
    ]
