# Generated by Django 4.0 on 2023-01-04 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_remove_book_isreturned_alter_borrowing_isreturned'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='borrowed',
            field=models.IntegerField(default=0),
        ),
    ]
