# Generated by Django 4.0 on 2023-01-04 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_book_borrowed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='borrowed',
            field=models.IntegerField(default=0, help_text='Number of times book is borrowed'),
        ),
    ]
